package main

import (
	"go/token"
	"strings"
	"testing"
)

func mustReflow(t *testing.T, src string) string {
	t.Helper()
	fset := token.NewFileSet()
	out, err := reflowSource(fset, "test.go", src)
	if err != nil {
		t.Fatalf("reflowSource: %v", err)
	}
	return out
}

func TestReflowExportedFuncDoc(t *testing.T) {
	src := `// pkg.go implements the pkg package.

package pkg

// LoadPortfolio reads every position file in dir and validates each one against the schema.
// It merges the valid files into a single Portfolio, and it returns an error if any file fails validation or two files declare the same position ID.
func LoadPortfolio(dir string) (*Portfolio, error) {
	return nil, nil
}
`
	want := `// pkg.go implements the pkg package.

package pkg

// LoadPortfolio reads every position file in dir and validates each one against the schema.
// It merges the valid files into a single Portfolio,
// and it returns an error if any file fails validation or two files declare the same position ID.
func LoadPortfolio(dir string) (*Portfolio, error) {
	return nil, nil
}
`
	got := mustReflow(t, src)
	if got != want {
		t.Errorf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestUnexportedFuncLeftAlone(t *testing.T) {
	src := `// pkg.go implements the pkg package.

package pkg

// loadPortfolio reads every position file in dir and validates each one against the schema.
// It merges the valid files into a single Portfolio, and returns an error on failure.
func loadPortfolio(dir string) {}
`
	got := mustReflow(t, src)
	if got != src {
		t.Errorf("unexported decl doc was reflowed, want left alone:\n%s", got)
	}
}

func TestSingleLineCommentLeftAlone(t *testing.T) {
	src := `// pkg.go implements the pkg package.

package pkg

// Foo does a thing.
func Foo() {}
`
	got := mustReflow(t, src)
	if got != src {
		t.Errorf("single-line doc comment was touched, want left alone:\n%s", got)
	}
}

func TestGoGenerateDirectiveLeftAlone(t *testing.T) {
	src := `// pkg.go implements the pkg package.

package pkg

// Foo does a thing across several files, and it needs a mock for testing purposes.
//go:generate mockgen -source=foo.go
func Foo() {}
`
	got := mustReflow(t, src)
	if got != src {
		t.Errorf("directive-adjacent doc comment was touched, want left alone:\n%s", got)
	}
}

func TestIndentedCodeExampleLeftAlone(t *testing.T) {
	src := `// pkg.go implements the pkg package.

package pkg

// Foo does a thing, and here is an example of calling it in practice.
//
//	Foo()
func Foo() {}
`
	got := mustReflow(t, src)
	if got != src {
		t.Errorf("comment block with indented code example was touched, want left alone:\n%s", got)
	}
}

func TestGeneratedFileLeftAlone(t *testing.T) {
	src := `// Code generated by foogen. DO NOT EDIT.

package pkg

// Foo does a thing, and it needs no further explanation beyond this single sentence run on long.
func Foo() {}
`
	got := mustReflow(t, src)
	if got != src {
		t.Errorf("generated file was touched, want left alone:\n%s", got)
	}
}

func TestSingleLineGroupLeftAlone(t *testing.T) {
	// A comment that already occupies exactly one physical source line is left alone regardless of
	// length -- there is no existing hard-wrap to reflow, matching pydocreflow.py's own
	// single-line-docstring/single-line-comment-block skip.
	src := `// Package pkg provides utilities for testing this reflow tool, and it exists solely for that purpose.
package pkg
`
	got := mustReflow(t, src)
	if got != src {
		t.Errorf("single-physical-line doc comment was reflowed, want left alone:\n%s", got)
	}
}

func TestPackageDocComment(t *testing.T) {
	src := `// Package pkg provides utilities for testing this reflow tool, and it
// exists solely for that purpose.
package pkg
`
	want := `// Package pkg provides utilities for testing this reflow tool,
// and it exists solely for that purpose.
package pkg
`
	got := mustReflow(t, src)
	if got != want {
		t.Errorf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestFileHeaderAndPackageDocBothReflowed(t *testing.T) {
	src := `// pkg.go implements the pkg package, and this header line alone is
// long enough to want a break.

// Package pkg provides utilities for testing, and this doc comment is
// also long enough to want a break.
package pkg
`
	got := mustReflow(t, src)
	if !strings.Contains(got, "pkg.go implements the pkg package,\n") {
		t.Errorf("file header was not reflowed:\n%s", got)
	}
	if !strings.Contains(got, "// Package pkg provides utilities for testing,\n") {
		t.Errorf("package doc was not reflowed:\n%s", got)
	}
}

func TestGroupedConstDocOnExportedSpec(t *testing.T) {
	src := `// pkg.go implements the pkg package.

package pkg

const (
	// MaxRetries caps the number of retry attempts, and it exists to
	// bound worst-case latency under failure.
	MaxRetries = 3
)
`
	want := `// pkg.go implements the pkg package.

package pkg

const (
	// MaxRetries caps the number of retry attempts,
	// and it exists to bound worst-case latency under failure.
	MaxRetries = 3
)
`
	got := mustReflow(t, src)
	if got != want {
		t.Errorf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestStructFieldDocLeftAlone(t *testing.T) {
	src := `// pkg.go implements the pkg package.

package pkg

// Config holds settings.
type Config struct {
	// Timeout bounds how long a request may run, and callers should set it explicitly rather than relying on the zero value.
	Timeout int
}
`
	got := mustReflow(t, src)
	if got != src {
		t.Errorf("struct field doc comment was touched, want left alone (out of scope):\n%s", got)
	}
}

func TestDocCommentHeadingLeftAlone(t *testing.T) {
	src := `// pkg.go implements the pkg package.

package pkg

// Foo does a thing.
//
// # Deprecated
//
// Use Bar instead, and remove all call sites before the next major release.
func Foo() {}
`
	got := mustReflow(t, src)
	if got != src {
		t.Errorf("doc comment containing a Go 1.19 heading was touched, want left alone:\n%s", got)
	}
}

func TestDocCommentListLeftAlone(t *testing.T) {
	src := `// pkg.go implements the pkg package.

package pkg

// Foo supports three modes:
//
//   - fast, which skips validation entirely and trusts the caller
//   - safe, which validates every field before proceeding
//   - strict, which also rejects unknown fields
func Foo() {}
`
	got := mustReflow(t, src)
	if got != src {
		t.Errorf("doc comment containing a Go 1.19 list was touched, want left alone:\n%s", got)
	}
}

func TestIdempotent(t *testing.T) {
	src := `// pkg.go implements the pkg package.

package pkg

// LoadPortfolio reads every position file in dir and validates each one against the schema.
// It merges the valid files into a single Portfolio,
// and it returns an error if any file fails validation or two files declare the same position ID.
func LoadPortfolio(dir string) (*Portfolio, error) {
	return nil, nil
}
`
	got := mustReflow(t, src)
	if got != src {
		t.Errorf("already-reflowed doc comment was changed, want no-op:\n%s", got)
	}
}
