// drift_test.go asserts that every command in the lyx cobra tree has a non-empty
// Short description. This is the structural self-documentation invariant: if a
// developer adds a subcommand without a Short, this test fails at CI time rather
// than silently producing a help tree with blank entries.

package main

import (
	"fmt"
	"testing"

	"github.com/spf13/cobra"
)

// TestDriftGuard_AllCommandsHaveShort walks the full cobra command tree produced
// by newRoot() and asserts that every command carries a non-empty Short string.
// It tolerates cobra's auto-generated "help" and "completion" subtrees by skipping
// them and their descendants, because those are infrastructure commands whose Short
// may be generated by cobra itself or by shell-completion plugin code outside our
// control.
func TestDriftGuard_AllCommandsHaveShort(t *testing.T) {
	root := newRoot()
	// Traverse the tree recursively and collect violations.
	violations := collectMissingShorts(root)
	for _, v := range violations {
		t.Errorf("command %q has no Short description", v)
	}
}

// collectMissingShorts performs a depth-first walk of the command tree rooted at
// cmd. It skips the "help" and "completion" subtrees because those are managed by
// cobra and their Short strings may be set outside the lyx codebase. All other
// commands must have a non-empty Short — the domain contract for self-documentation.
func collectMissingShorts(cmd *cobra.Command) []string {
	// Skip cobra's infrastructure subtrees; they are not domain commands.
	name := cmd.Name()
	if name == "help" || name == "completion" {
		return nil
	}

	var violations []string

	if cmd.Short == "" {
		violations = append(violations, fmt.Sprintf("%s", cmd.CommandPath()))
	}

	for _, child := range cmd.Commands() {
		violations = append(violations, collectMissingShorts(child)...)
	}

	return violations
}
