// lint_test.go drives the break classification over base and new text pairs.

package commentlint

import (
	"slices"
	"strings"
	"testing"
)

// source wraps comment lines in a Go file, one `//` line each, above a declaration.
func source(commentLines ...string) string {
	return "package p\n\n" + strings.Join(commentLines, "\n") + "\nfunc F() {}\n"
}

// flaggedLines returns the line numbers findNewWrappedBreaks reports.
func flaggedLines(baseText, newText string) []int {
	var lines []int
	for _, finding := range findNewWrappedBreaks("p.go", baseText, newText) {
		lines = append(lines, finding.Line)
	}
	return lines
}

func TestFindNewWrappedBreaks(t *testing.T) {
	t.Parallel()

	wrapped := source("// the first line of a", "// fixed-column wrapped comment", "// that goes on.")
	flaggedWrapped := []int{3, 4}

	tests := []struct {
		name string
		base string
		new  string
		want []int
	}{
		{"a fixed-column-wrapped new comment is flagged", "", wrapped, flaggedWrapped},
		{"an untouched wrapped block is not flagged", wrapped, wrapped, nil},
		{
			"an untouched wrapped line is not flagged when an edit adds a break elsewhere in the file",
			wrapped,
			wrapped + "\n// one more short line.\n// and another.\nfunc G() {}\n",
			nil,
		},
		{
			"a break an edit creates in a legacy wrapped block is flagged",
			wrapped,
			source("// the first line of a", "// fixed-column wrapped", "// comment that goes on."),
			[]int{4},
		},
		{
			"fixing one flagged break leaves the block's other breaks unflagged",
			wrapped,
			source("// the first line of a fixed-column wrapped comment", "// that goes on."),
			nil,
		},
		{"a sentence end passes", "", source("// ends a sentence.", "// starts the next."), nil},
		{"a sentence end before a closing parenthesis passes", "", source("// ends a sentence (like this.)", "// starts the next."), nil},
		{"a sentence end before a closing quote passes", "", source(`// ends with "a quote."`, "// starts the next."), nil},
		{"a sentence end before a closing backtick passes", "", source("// ends with `code.`", "// starts the next."), nil},
		{"a question mark passes", "", source("// is it a sentence?", "// yes."), nil},
		{"a colon passes", "", source("// the cases are:", "// one, two."), nil},
		{"a semicolon passes", "", source("// first clause;", "// second clause."), nil},
		{"a comma before a conjunction passes", "", source("// one thing happens,", "// but another does not."), nil},
		{"a comma before yet passes", "", source("// one thing happens,", "// yet another does not."), nil},
		{"a comma before so passes", "", source("// one thing happens,", "// so another does too."), nil},
		{"a comma before anything else is flagged", "", source("// one thing, then", "// another."), []int{3}},
		{"a block's blank separator line ends the paragraph", "", source("// first paragraph without a stop", "//", "// second paragraph."), nil},
		{"a directive line ends its block, so the prose above it is still checked", "", source("// a wrapped", "// line", "//lyx:guard"), []int{3}},
		{"an indented code paragraph is never flagged", "", source("// a wrapped", "// line", "//\tcode"), nil},
		{"a list item paragraph is never flagged", "", source("// a wrapped", "// line", "// - item"), nil},
		{"a heading paragraph is never flagged", "", source("// a wrapped", "// line", "// # Heading"), nil},
		{"a wrapped paragraph beside a heading paragraph is flagged", "", source("// # Heading", "//", "// a wrapped", "// line."), []int{5}},
		{"a wrapped paragraph beside a list paragraph is flagged", "", source("// - item", "//", "// a wrapped", "// line."), []int{5}},
		{"an end-of-line comment is no block", "", "package p\n\nvar x = 1 // wrapped\n// line.\n", nil},
		{"a generated file is never flagged", "", "// Code generated by tool. DO NOT EDIT.\n\n" + wrapped, nil},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			if got := flaggedLines(tt.base, tt.new); !slices.Equal(got, tt.want) {
				t.Errorf("flagged lines = %v; want %v", got, tt.want)
			}
		})
	}
}

func TestParseNameStatus(t *testing.T) {
	t.Parallel()

	got := parseNameStatus("M\x00a.go\x00A\x00b.go\x00D\x00c.go\x00R100\x00old.go\x00new.go\x00")
	want := []fileChange{
		{path: "a.go", basePath: "a.go"},
		{path: "b.go"},
		{path: "new.go", basePath: "old.go"},
	}
	if !slices.Equal(got, want) {
		t.Errorf("parseNameStatus() = %+v; want %+v", got, want)
	}
}
