package main

import (
	"fmt"
	"regexp"
	"strings"
)

// measuredPackage is one package a redundancy run measured, as the splice sees it.
type measuredPackage struct {
	pkg     string // short import path
	section string // the rendered section, ignored when noTests is set
	noTests bool   // the package lists no tests, so it has no section
	failed  bool   // the package failed to list or build; section is its error section
}

var (
	reportTagsLine = regexp.MustCompile("(?m)^Generated by .* under the tags `([^`]*)`\\.$")
	sectionHeading = regexp.MustCompile(`(?m)^## (.+)$`)
)

// splitPatterns splits the -pkg flag value into its comma-separated package patterns.
func splitPatterns(pkgFlag string) []string {
	var patterns []string
	for _, p := range strings.Split(pkgFlag, ",") {
		if p = strings.TrimSpace(p); p != "" {
			patterns = append(patterns, p)
		}
	}
	return patterns
}

// requireSameTags refuses an existing report made under a tag set other than tags, read from the header line renderReport writes.
func requireSameTags(report, tags string) error {
	m := reportTagsLine.FindStringSubmatch(report)
	if m == nil {
		return fmt.Errorf("the existing report has no tags header line, so its tag set cannot be checked")
	}
	if m[1] != tags {
		return fmt.Errorf("the existing report was made under the tags %q and this run uses %q: rerun with -tags %s, or delete the report to write it whole", m[1], tags, m[1])
	}
	return nil
}

// reportSection is one package's section of an existing report, without the blank line that separates it from the next.
type reportSection struct {
	pkg  string
	text string
}

// spliceReport rewrites only the measured packages' sections of an existing report.
// A measured package's section is replaced, inserted in import-path order when it has none yet, or removed when the package lists no tests.
// A failed package keeps its old section and gets its error section only when it had none.
// The header and every section of an unmeasured package come back byte-identical.
// It refuses, writing nothing, when the existing report was made under a different tag set.
func spliceReport(existing, tags string, measured []measuredPackage) (string, error) {
	if err := requireSameTags(existing, tags); err != nil {
		return "", err
	}

	header, sections := splitReport(existing)
	for _, m := range measured {
		at := -1
		for i, s := range sections {
			if s.pkg == m.pkg {
				at = i
			}
		}
		switch {
		case m.noTests:
			if at >= 0 {
				sections = append(sections[:at], sections[at+1:]...)
			}
		case m.failed && at >= 0:
		case at >= 0:
			sections[at].text = m.section
		default:
			insert := len(sections)
			for i, s := range sections {
				if s.pkg > m.pkg {
					insert = i
					break
				}
			}
			sections = append(sections, reportSection{})
			copy(sections[insert+1:], sections[insert:])
			sections[insert] = reportSection{pkg: m.pkg, text: m.section}
		}
	}

	var b strings.Builder
	b.WriteString(header)
	for _, s := range sections {
		b.WriteString("\n")
		b.WriteString(s.text)
	}
	return b.String(), nil
}

// splitReport cuts a report into its header, ending in one newline, and its package sections in file order.
func splitReport(report string) (string, []reportSection) {
	starts := sectionHeading.FindAllStringSubmatchIndex(report, -1)
	if len(starts) == 0 {
		return report, nil
	}
	header := strings.TrimRight(report[:starts[0][0]], "\n") + "\n"
	sections := make([]reportSection, len(starts))
	for i, loc := range starts {
		end := len(report)
		if i+1 < len(starts) {
			end = starts[i+1][0]
		}
		sections[i] = reportSection{
			pkg:  report[loc[2]:loc[3]],
			text: strings.TrimRight(report[loc[0]:end], "\n") + "\n",
		}
	}
	return header, sections
}
